name: Lint Project
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  'Run-Linter':
    runs-on: ubuntu-18.04
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - name: Prepare
        run: npm ci
      - name: Lint
        uses: mooyoul/tslint-actions@v1.1.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pattern: 'src/**/*.ts'
